(function(){var l=Handlebars.template;(Handlebars.discovery=Handlebars.discovery||{}).templates=l(function(h,k,f,i,a){function b(a,d,b){var e="",c,m;e+='\n        <li class="discovery-post" id="discovery-link-';(c=f.domIdSuffix)?c=c.call(a,{hash:{},data:d}):(c=a.domIdSuffix,c=typeof c===r?c.apply(a):c);e+=o(c)+'">\n            <header class="discovery-post-header">\n                <h3 title="';(c=f.title)?c=c.call(a,{hash:{},data:d}):(c=a.title,c=typeof c===r?c.apply(a):c);e+=o(c)+'">\n                    <a ';
if((c=j.invokePartial(i.linkAttributes,"linkAttributes",a,f,i,d))||c===0)e+=c;e+=' data-role="discovery-thread-title" class="title publisher-anchor-color line-truncate" data-line-truncate="2">\n                        '+o(f.html.call(a,a.title,{hash:{},data:d}))+"\n                    </a>\n\n                    ";if((m=f["if"].call(a,(c=b.variant,c==null||c===!1?c:c.inlineMeta),{hash:{},inverse:j.noop,fn:j.program(3,g,d),data:d}))||m===0)e+=m;e+="\n\n                </h3>\n\n                ";if((m=
f.unless.call(a,(c=b.variant,c==null||c===!1?c:c.inlineMeta),{hash:{},inverse:j.noop,fn:j.program(11,w,d),data:d}))||m===0)e+=m;e+="\n\n            </header>\n\n            ";if((m=f["if"].call(a,(c=b.variant,c==null||c===!1?c:c.contentPreviews)&&a.preview,{hash:{},inverse:j.noop,fn:j.program(16,n,d),data:d}))||m===0)e+=m;e+="\n\n        </li>\n    ";return e}function g(a,d){var b="",e;b+="\n                        ";if((e=f["if"].call(a,a.posts>0,{hash:{},inverse:j.program(6,m,d),fn:j.program(4,
c,d),data:d}))||e===0)b+=e;b+="\n                        ";if((e=f["if"].call(a,a.brand,{hash:{},inverse:j.noop,fn:j.program(9,x,d),data:d}))||e===0)b+=e;b+="\n                    ";return b}function c(a,d){var c="",e;c+='\n                            <span class="inline-meta">\n                                ';if((e=j.invokePartial(i.discoveryPostCount,"discoveryPostCount",a,f,i,d))||e===0)c+=e;c+="\n                            </span>\n                        ";return c}function m(a,c){var b="",
e;b+="\n                            ";if((e=f["if"].call(a,a.createdAgo,{hash:{},inverse:j.noop,fn:j.program(7,d,c),data:c}))||e===0)b+=e;b+="\n                        ";return b}function d(a,d){var c="",e;c+='\n                                <span class="inline-meta">';(e=f.createdAgo)?e=e.call(a,{hash:{},data:d}):(e=a.createdAgo,e=typeof e===r?e.apply(a):e);c+=o(e)+"</span>\n                            ";return c}function x(a,d){var c="",e;c+='\n                            <span class="inline-meta">\n                                ';
(e=f.brand)?e=e.call(a,{hash:{},data:d}):(e=a.brand,e=typeof e===r?e.apply(a):e);c+=o(e)+"\n                            </span>\n                        ";return c}function w(a,c){var d="",e;d+='\n                    <ul class="meta">\n                        ';if((e=f["if"].call(a,a.posts>0,{hash:{},inverse:j.noop,fn:j.program(12,u,c),data:c}))||e===0)d+=e;d+="\n                        ";if((e=f["if"].call(a,a.createdAgo,{hash:{},inverse:j.noop,fn:j.program(14,q,c),data:c}))||e===0)d+=e;d+="\n                    </ul>\n                ";
return d}function u(a,d){var c="",e;c+='\n                            <li class="comments">\n                                ';if((e=j.invokePartial(i.discoveryPostCount,"discoveryPostCount",a,f,i,d))||e===0)c+=e;c+="\n                            </li>\n                        ";return c}function q(a,c){var d="",e;d+='\n                            <li class="time">';(e=f.createdAgo)?e=e.call(a,{hash:{},data:c}):(e=a.createdAgo,e=typeof e===r?e.apply(a):e);d+=o(e)+"</li>\n                        ";
return d}function n(a,c){var d="",e;d+="\n                ";if((e=j.invokePartial(i.discoveryContentPreview,"discoveryContentPreview",a,f,i,c))||e===0)d+=e;d+="\n            ";return d}function s(){return'target="_blank" rel="nofollow"'}function t(a,d){var c="";c+="\n        "+o(f.t.call(a,gettext("1 comment"),{hash:{},data:d}))+"\n    ";return c}function l(a,d){var c="";c+="\n        "+o(f.t.call(a,gettext("%(numPosts)s comments"),{hash:{numPosts:a.posts},data:d}))+"\n    ";return c}function y(a,
d,c){var e="",b;e+='\n        <section id="';(b=f.id)?b=b.call(a,{hash:{},data:d}):(b=a.id,b=typeof b===r?b.apply(a):b);e+=o(b)+'" class="';(b=f.className)?b=b.call(a,{hash:{},data:d}):(b=a.className,b=typeof b===r?b.apply(a):b);e+=o(b)+'">\n            <header class="discovery-col-header">\n\n                ';if((b=f["if"].call(a,d.index===d.length-1,{hash:{},inverse:j.noop,fn:j.program(30,z,d),data:d}))||b===0)e+=b;e+="\n\n                ";if((b=f["if"].call(a,a.type==="organic",{hash:{},inverse:j.noop,
fn:j.programWithDepth(A,d,c),data:d}))||b===0)e+=b;e+="\n                ";if((b=f["if"].call(a,a.type==="promoted",{hash:{},inverse:j.noop,fn:j.program(34,B,d),data:d}))||b===0)e+=b;e+='\n\n            </header>\n            <ul class="discovery-posts">\n            </ul>\n        </section>\n    ';return e}function z(a,d){var c="";c+='\n                    \n                    <div class="discovery-options">\n                        <span class="publisher-anchor-color"><a href="#" class="discovery-help" data-action="discovery-help">'+
o(f.t.call(a,gettext("What's this?"),{hash:{},data:d}))+"</a></span>\n                    </div>\n                ";return c}function A(a,d,c){var e="";e+="\n                    <h2>"+o(f.t.call(a,gettext("Also on %(forumName)s"),{hash:{forumName:{partial:"forumName",context:c.forum,executePartial:!0}},data:d}))+"</h2>\n                ";return e}function B(a,d){var c="";c+="\n                    <h2>"+o(f.t.call(a,gettext("Around The Web"),{hash:{},data:d}))+"</h2>\n                ";return c}this.compilerInfo=
[2,">= 1.0.0-rc.3"];var f=f||h.helpers,i=i||h.partials,a=a||{},h="",p,j=this,r="function",o=this.escapeExpression;if((p=f.partial.call(k,"discoveryCollection",{hash:{},inverse:j.noop,fn:j.program(1,function(a,d){var c="",e;c+="\n    ";if((e=f.each.call(a,a.collection,{hash:{},inverse:j.noop,fn:j.programWithDepth(b,d,a),data:d}))||e===0)c+=e;c+="\n";return c},a),data:a}))||p===0)h+=p;h+="\n\n";if((p=f.partial.call(k,"linkAttributes",{hash:{},inverse:j.noop,fn:j.program(18,function(a,d){var c="",e;
c+='\n    href="';(e=f.redirectUrl)?e=e.call(a,{hash:{},data:d}):(e=a.redirectUrl,e=typeof e===r?e.apply(a):e);c+=o(e)+'" ';if((e=f["if"].call(a,a.brand,{hash:{},inverse:j.noop,fn:j.program(19,s,d),data:d}))||e===0)c+=e;c+="\n";return c},a),data:a}))||p===0)h+=p;h+="\n\n";if((p=f.partial.call(k,"discoveryContentPreview",{hash:{},inverse:j.noop,fn:j.program(21,function(a,d){var D;var C;var v;var c="",e;c+="\n    <a ";if((e=j.invokePartial(i.linkAttributes,"linkAttributes",a,f,i,d))||e===0)c+=e;c+=
' class="top-comment" data-role="discovery-top-comment">\n        <img src="'+o((C=(v=(e=(e=a.preview,e==null||e===!1?e:e.author),e==null||e===!1?e:e.avatar),e=v,e==null||e===!1?e:e.cache),e=C,typeof e===r?e.apply(a):e))+'" alt="'+o(f.t.call(a,gettext("Avatar"),{hash:{},data:d}))+'" data-role="discovery-avatar">\n        <p><span class="user" data-role="discovery-top-comment-author">'+o((D=(e=(e=a.preview,e==null||e===!1?e:e.author),e==null||e===!1?e:e.name),e=D,typeof e===r?e.apply(a):e))+'</span> — <span data-role="discovery-top-comment-snippet" class="line-truncate" data-line-truncate="3">'+
o((e=(e=a.preview,e==null||e===!1?e:e.plaintext),typeof e===r?e.apply(a):e))+"</span></p>\n    </a>\n";return c},a),data:a}))||p===0)h+=p;h+="\n\n";if((p=f.partial.call(k,"discoveryPostCount",{hash:{},inverse:j.noop,fn:j.program(23,function(a,d){var c="",e;c+="\n    ";if((e=f["if"].call(a,a.posts===1,{hash:{},inverse:j.program(26,l,d),fn:j.program(24,t,d),data:d}))||e===0)c+=e;c+="\n";return c},a),data:a}))||p===0)h+=p;h+="\n\n";if((p=f.partial.call(k,"discoveryMain",{hash:{},inverse:j.noop,fn:j.programWithDepth(function(a,
d,c){var e="",b;e+='\n<div id="';(b=f.id)?b=b.call(a,{hash:{},data:d}):(b=a.id,b=typeof b===r?b.apply(a):b);e+=o(b)+'" class="discovery-main">\n    <div id="discovery-note" style="display:none;">\n        <div class="alert">\n        <a href="#" class="close" data-action="discovery-help-close" title="'+o(f.t.call(a,gettext("Close this box"),{hash:{},data:d}))+'">\u00d7</a>\n        '+o(f.t.call(a,gettext("Disqus helps you find new and interesting content, discussions and products. Some sponsors and ecommerce sites may pay us for these recommendations and links. %(learnMore)s or %(feedback)s."),
{hash:{learnMore:{partial:"learnMore",context:c,executePartial:!0},feedback:{partial:"feedback",context:c,executePartial:!0}},data:d}))+"\n        </div>\n    </div>\n\n    ";if((b=f.each.call(a,a.sections,{hash:{},inverse:j.noop,fn:j.programWithDepth(y,d,a),data:d}))||b===0)e+=b;e+="\n\n</div>\n";return e},a,k),data:a}))||p===0)h+=p;h+="\n\n";if((p=f.partial.call(k,"learnMore",{hash:{},inverse:j.noop,fn:j.program(36,function(a,d){var c="";c+='\n    <a href="http://help.disqus.com/customer/portal/articles/666278-introducing-promoted-discovery-and-f-a-q-"\n        target="_blank">'+
o(f.t.call(a,gettext("Learn more"),{hash:{},data:d}))+"</a>\n";return c},a),data:a}))||p===0)h+=p;h+="\n\n";if((p=f.partial.call(k,"feedback",{hash:{},inverse:j.noop,fn:j.program(38,function(a,d){var c="";c+='\n    <a href="https://www.surveymonkey.com/s/GHK872T" target="_blank">\n        '+o(f.t.call(a,gettext("give us feedback"),{hash:{},data:d}))+"</a>\n";return c},a),data:a}))||p===0)h+=p;h+="\n\n";if((p=f.partial.call(k,"forumName",{hash:{},inverse:j.noop,fn:j.program(40,function(a,d){var c=
"",b;c+="\n    <strong>";(b=f.name)?b=b.call(a,{hash:{},data:d}):(b=a.name,b=typeof b===r?b.apply(a):b);c+=o(b)+"</strong>\n";return c},a),data:a}))||p===0)h+=p;h+="\n";return h})})();
DISQUS.define("discovery.collections",function(){var l=DISQUS.JSON,h=_.strip,k=DISQUS.use("discovery.helpers"),f=DISQUS.use("discovery.models"),i=Backbone.Collection.extend({url:function(a){return DISQUS.api.getURL(a)},fetch:function(a){a=a||{};a.reset=!0;return Backbone.Collection.prototype.fetch.call(this,a)},parse:function(a){return a.response}}),a=function(a){var c=a.prototype;return a.extend({url:function(){return c.url.call(this,"discovery/listTopPost.json")},parse:function(a){for(var a=c.parse.call(this,
a),d=0,b=a.length;d<b;d++)a[d].plaintext=h(a[d].message);return a}})}(i),b=function(a){var c=a.prototype;return a.extend({initialize:function(a,c){this.model=f[this.modelName];this.sourceThread=c.sourceThread;this.modelAttributes=c.modelAttributes;this.getBanditJSON=_.memoize(this.getBanditJSON)},parse:function(a){a=c.parse.call(this,a);if("bandit"in a)this.bandit=a.bandit,a=a.results;if(!_.isArray(a))return[];_.each(a,function(a){_.extend(a,this.modelAttributes)},this);return a},getBanditJSON:function(){return l.stringify(this.bandit)}})}(i),
g=function(a){var c=a.prototype;return a.extend({modelName:"RelatedThread",url:function(){return c.url.call(this,"discovery/listRelated.json")},parse:function(a){return this.rejectInvalid(c.parse.call(this,a))},rejectInvalid:function(a){var c=this.sourceThread;if(DISQUS.debug)return a.slice();return _.filter(a,function(a){if(a.id==c.id||a.link==c.link)return this.reportInvalid(a,"Link or id of related thread points back to thread on this page (circular reference)"),!1;if(a.title.search(/^https?:\/\//)===
0)return this.reportInvalid(a,"Title looks like a url (begins with http:// or https://)"),!1;return!0},this)},reportInvalid:function(a,c){var d=k.log;d("An organic link failed validation:",a.title,a.link,"(id =",a.id+")");d("Reason:",c)}})}(b),c=function(a){var c=a.prototype;return a.extend({modelName:"Advertisement",url:function(){return c.url.call(this,"discovery/listPromoted.json")}})}(b),m=function(a){var c=a.prototype;return a.extend({modelName:"TempestAdvertisement",url:"//tempest.services.disqus.com/listPromoted",
fetch:function(a){a=a||{};a.dataType="jsonp";a.data=a.data||{};if(_.has(a.data,"limit"))a.data.count=a.data.limit,delete a.data.limit;_.has(a.data,"thread")&&delete a.data.thread;return c.fetch.call(this,a)}})}(c),a={PostCollection:a,RelatedThreadCollection:g,AdvertisementCollection:c,TempestAdvertisementCollection:m};if(DISQUS.testing)a.BaseCollection=i,a.BaseContentCollection=b;return a});
DISQUS.define("discovery",function(){var l=DISQUS.use("discovery.collections"),h=DISQUS.use("discovery.views"),k=DISQUS.use("discovery.helpers"),f=Backbone.Model.extend({defaults:{name:"promoted",inlineMeta:!0,contentPreviews:!1,promotedEnabled:!0,topPlacementEnabled:!1,isExperiment:!1,redirectUrl:"//redirect.disqus.com/url",listRelatedLimit:null,listPromotedLimit:null,httpTimeout:1E4,sourceThread:null,sourceForum:null,useNewAdserver:!1,help:!1,display:!1,columnEveningEnabled:!0,numColumns:2,minPerColumn:1,
maxPerColumn:4,toleranceCoefficient:1.2,minWidthForColumnLayout:440,containerId:"discovery",topPlacementContainerId:"discovery-top",innerContainerName:"discovery-main",sectionNames:["col-organic","col-promoted"],collectionTagName:"ul",collectionClassName:"discovery-posts",consoleLoggingEnabled:DISQUS.debug,lineTruncationEnabled:!0,session:null,js:null,css:null},initialize:function(){var a=this;a.get("useNewAdserver")&&(a.set("isExperiment",!0),a.set("name","tempest"));a.createDataReferences();a.set("innerContainerId",
a.get("innerContainerName")+"-"+a.cid);a.set("sectionIds",_.map(a.get("sectionNames"),function(b){return b+"-"+a.cid}));var b=a.get("session");a.get("topPlacementEnabled")&&b.isAnonymous()&&a.set("containerId",a.get("topPlacementContainerId"));a.once("change:display",function(){a.onComplete()});_.bindAll(a,"getContentPreviews","validateData","showData");a.run()},commonClickMetadata:function(){var a=this.get("sourceThread"),b=this.get("sourceForum"),a={redirectUrl:this.get("redirectUrl"),sourceThreadId:a.id,
forumId:b.pk,forum:b.id,majorVersion:this.majorVersion(),variant:this.get("name"),isExperiment:this.get("isExperiment")};if((b=this.get("session"))&&b.isRegistered())a.userId=b.user.id;return a},createDataReferences:function(){function a(){this.sourceThread=b.get("sourceThread");this.modelAttributes=b.commonClickMetadata()}var b=this;b.collections=[];var g=new a;g.modelAttributes.createdAgo=!0;this.threads=new l.RelatedThreadCollection(null,g);this.collections.push(this.threads);if(this.get("promotedEnabled"))this.ads=
new (this.get("useNewAdserver")?l.TempestAdvertisementCollection:l.AdvertisementCollection)(null,new a),this.collections.push(this.ads)},run:function(){var a=_.bind(this.onComplete,this);this.getData().then(this.validateData).then(this.showData).otherwise(a)},getData:function(){function a(){this.timeout=b.get("httpTimeout");this.data={thread:b.get("sourceThread").id,limit:g/b.collections.length*b.get("maxPerColumn")}}var b=this,g=b.get("numColumns"),c=new a;if(b.has("listRelatedLimit"))c.data.limit=
b.get("listRelatedLimit");var m=b.listRelatedRequest=when(b.threads.fetch(c));b.get("contentPreviews")&&(m=m.then(b.getContentPreviews));if(!b.get("promotedEnabled"))return m;c=new a;if(b.has("listPromotedLimit"))c.data.limit=b.get("listPromotedLimit");c=b.listPromotedRequest=when(b.ads.fetch(c));return when.join(m,c)},getContentPreviews:function(){var a=this.threads.pluck("id"),b=this.collections.length,g=this.get("numColumns"),c=this.get("minPerColumn");if(a.length<g/b*c)return when.resolve();this.previews=
new l.PostCollection;return(this.listTopPostRequest=when(this.previews.fetch({data:{thread:a},timeout:this.get("httpTimeout")}))).then(_.bind(this.attachPreviews,this))},attachPreviews:function(){var a=this;a.previews.each(function(b){var g=b.get("thread");(g=a.threads.get(g.id||g))&&g.set("preview",b)})},validateCollections:function(){for(var a=this.collections,b=a.length,g=this.get("numColumns"),c=this.get("minPerColumn"),m,d;b>0;)if(d=g/a.length*c,m=a[--b],m.length<d)a.splice(b,1),b=a.length;b=
a.length;if(b>0){g=g/b*this.get("maxPerColumn");for(c=0;c<b;c++)m=a[c],m.length>g&&m.reset(m.slice(0,g))}},validateData:function(){k.isMobile()&&this.ads&&this.ads.length>0&&this.ads.remove(this.ads.where({mobile:!1}));this.validateCollections();if(this.collections.length===0)throw"Not enough data";},showData:function(){function a(a){_.extend(this,a);this.appContext=b.toJSON()}var b=this,g=document.getElementById(b.get("containerId"));if(!g)throw"No container on the DOM";g=b.mainView=new h.MainView(new a({el:g,
model:b}));g.render();var c=b.get("sectionIds"),m=b.get("collectionTagName"),d=b.get("collectionClassName");b.views=_.map(b.collections,function(b,g){return new h.BaseCollectionView(new a({collection:b,el:$("#"+c[g]+" "+m+"."+d)}))});b.views.length===2&&g.$el.find("#"+b.get("innerContainerId")).addClass("doublesection");_.invoke(b.views,"render");if(b.get("columnEveningEnabled")&&g.$el.width()>b.get("minWidthForColumnLayout"))(new h.TwoColumn({views:b.views,fudge:this.get("toleranceCoefficient")})).render();
else{var f=_.min(_.pluck(b.collections,"length"));_.each(b.views,function(a){for(;a.collection.length>f;)a.collection.pop()})}b.set("display",!0)},onComplete:function(a){var b=k.log;if(this.onCompleteCalled)return b("Error: Final reporting function called more than once");this.onCompleteCalled=!0;a&&b("It looks like there was a problem:",a);this.report()},report:function(){var a=k.log,b=this.snapshot(),g=DISQUS.juggler.client("juggler");if(!g)return void a("Cannot report app state, no client found");
a("Sending analytics data about this Discovery impression:");a("init_discovery: ",b);g.emit("init_discovery",b);this.get("darkJester")&&DISQUS.juggler.client("jester",!0).emit("init_discovery",b)},majorVersion:function(){return this.get("promotedEnabled")?"midway":"metadata"},snapshot:function(){var a=this.collections,b=this.threads,b={major_version:this.majorVersion(),internal_organic:b.length,external_organic:0,promoted:0,display:this.get("display"),placement:this.get("containerId")===this.get("topPlacementContainerId")?
"top":"bottom"};if(this.get("promotedEnabled")){var g=this.ads;_.extend(b,{promoted:g.length,promoted_ids:DISQUS.JSON.stringify(g.pluck("advertisement_id"))})}a=_.extend.apply(_,[{}].concat(_.pluck(a,"bandit")));if(!_.isEmpty(a))b.bandit=DISQUS.JSON.stringify(a);if(this.get("isExperiment"))b.variant=this.get("name");return b}}),i={};if(DISQUS.testing)i.DiscoveryApp=f;i.init=function(a){var b=_.object(_.map(["lineTruncationEnabled","consoleLoggingEnabled"],function(b){return b in a?[b,a[b]]:[b,f.prototype.defaults[b]]}));
k.config(b);return new f(a)};return i});
DISQUS.define("discovery.views",function(){var l=DISQUS.use("discovery.helpers"),h=Backbone.View.extend({initialize:function(a){if(a&&a.appContext)this.appContext=a.appContext},getTemplateContext:function(){if(!this.appContext)return{};return{variant:this.appContext}},template:function(a,b){b=b||this.templateName;return DISQUS.renderBlock(b,a)}}),k=function(a){var b=a.prototype;return a.extend({events:{"click [data-redirect]":"handleClick"},handleClick:function(a){this.swapHref(a.currentTarget)},swapHref:function(a){a.setAttribute("data-href",
a.getAttribute("href"));a.setAttribute("href",a.getAttribute("data-redirect"));_.delay(function(){a.setAttribute("href",a.getAttribute("data-href"))},100)},templateName:"discoveryCollection",initialize:function(a){b.initialize.call(this,a);this.elementsSelector="li.discovery-post";this.$elements=this.$el.find(this.elementsSelector);a=this.collection;a.on("remove",this.remove,this);a.on("reset",this.render,this)},truncate:function(){this.$el.find(".line-truncate").each(function(a){a=$(a);l.lineTruncate(a,
{lines:a.attr("data-line-truncate"),ellipsis:!0})})},getTemplateContext:function(){var a=b.getTemplateContext.call(this);a.collection=this.collection.toJSON();var c=this.collection.at(0),g=c.has("id")?"organic-":"promoted-",f=c.idAttribute;_.each(a.collection,function(a){a.domIdSuffix=a[f];a.domIdSuffix=g+a.domIdSuffix});return a},render:function(){this.$el.html(this.template(this.getTemplateContext()));this.$elements=this.$el.find(this.elementsSelector);this.truncate();return this},remove:function(a,
c,b){if(arguments.length===0)return h.prototype.remove.call(this);var g=_.toArray(this.$elements),m=g.splice(b.index,1)[0];$(m).remove();this.$elements=$(g);return this}})}(h),f=function(a,b){this.modelIds=a||[];this.$elements=$(b||[])};_.extend(f.prototype,{height:function(){var a=this;a.heights=[];var b=$(a.$elements),d=b.first().offset().top,d=function(){var a=b.last().offset();return a.top+a.height}()-d,g=0;_.each(b,function(b){b=$(b).height();a.heights.push(b);g+=b});this.interstice=(d-g)/(b.length-
1);return d}});var i=function(){this.divideIntoColumns=function(){var a=this,b=a.subviews[0];a.left=new f;a.right=new f;var d=0;b.collection.each(function(g,f){var h=d++%2===0?"left":"right";a[h].modelIds.push(g.id);Array.prototype.push.call(a[h].$elements,b.$elements[f])})};this.removeOneFromColumn=function(a,b){var d=_.chain(a.modelIds).map(function(b,d){return[b,a.heights[d]]}).sortBy(function(a){return-1*a[1]}).find(function(a){return a[1]<=b}).value()[0],g=this.subviews[0].collection,f=g.models,
h=g.get(d),k=f.indexOf(h),d=[[],[]],n,s=f.length;for(n=0;n<s;n++)d[n%2].push(f[n]);f=d[k%2];f.splice(_.indexOf(f,h),1);f=[];h=(k+1)%2;for(n=0;n<s-1;n++)f.push(d[(n+h)%2].shift());g.reset(f)};this.balanceColumns=function(){var a=this.subviews[0],b=a.collection,d={};b.each(function(b,g){d[g]=a.$elements[g]});var g=l.balancedPartition(d),g=_.sortBy(g,"length"),f=g[0],h=b.models,k=Array(h.length);_.each(g[1],function(a,b){k[2*b]=h[b]});_.each(f,function(a,b){k[2*b+1]=h[b]});b.reset(h)};this.shortenColumn=
function(a,b){this.subviews[0].collection.length%2!==0&&a===this.left?this.removeOneFromColumn(a,this.fudge*b):this.balanceColumns()}},a=function(){this.divideIntoColumns=function(){var a=this.subviews,b=a[0],a=a[1];this.left=new f(b.collection.pluck(b.collection.model.prototype.idAttribute),b.$elements);this.right=new f(a.collection.pluck(a.collection.model.prototype.idAttribute),a.$elements)};this.shortenColumn=function(a,b){for(var d=a===this.left?this.right:this.left,g=b/d.$elements.length,f=
(a===this.left?this.subviews[0]:this.subviews[1]).collection,h=_.chain(a.modelIds).map(function(b,d){return[b,a.heights[d]]}).sortBy(function(a){return a[1]}).value(),k=[],n=0,i=b,i=g;h.length;){var l=h.pop(),v=l[0],l=l[1]+a.interstice;n+l>b&&(d=a);i=Math.abs(b-(n+l));i/=d.$elements.length;i>=g||(g=i,i=a.modelIds.indexOf(v),a.modelIds.splice(i,1),Array.prototype.splice.call(a.$elements,i,1),n+=l,k.push(v))}f.remove(k)}},b=function(b){this.fudge=b.fudge;this.subviews=b.views.slice(0,2);this.subviews.length===
1?i.call(this):a.call(this)};_.extend(b.prototype,{ascendingByHeight:function(){var a=this.left,b=this.right,a=[[a,a.height()],[b,b.height()]];return _.sortBy(a,function(a){return a[1]})},evenColumns:function(a){var b=this.ascendingByHeight(),d=b[0][0],g=b[0][1],f=b[1][0],b=b[1][1];if(g!==b){var g=b-g,h=this.fudge*g,b=_.find(f.heights,function(a){return a+f.interstice<h});if(!a&&b)return this.shortenColumn(f,g),this.divideIntoColumns(),this.evenColumns("do not recurse again");this.increaseMargins(d,
g)}},increaseMargins:function(a,b){var d=b/a.$elements.length;_.each(a.$elements,function(a){var a=$(a),b=parseInt(a.css("margin-bottom"),10)+d;a.css("margin-bottom",b+"px")});(a===this.left?this.right:this.left).$elements.css("clear",a===this.right?"left":"right")},render:function(){this.divideIntoColumns();this.evenColumns();return this}});var g=function(a){var b=a.prototype;return a.extend({templateName:"discoveryMain",events:{"click [data-action=discovery-help]":function(a){a.preventDefault();
this.model.set("help",!0)},"click [data-action=discovery-help-close]":function(a){a.preventDefault();this.model.set("help",!1)}},toggleHelp:function(a){this.$el.find("#discovery-note").toggle();a.trigger("resize")},initialize:function(a){b.initialize.call(this,a);this.model.on("change:display",this.show,this);this.model.on("change:help",this.toggleHelp,this);this.$el.css({position:"absolute",visibility:"hidden",display:"block"})},createSections:function(){var a=this.model,b=DISQUS.discovery.collections,
c=b.RelatedThreadCollection,g=b.AdvertisementCollection,f=a.get("sectionNames"),h=a.get("sectionIds");return _.map(a.collections,function(a,b){var d;a instanceof c?d="organic":a instanceof g&&(d="promoted");return{id:h[b],className:f[b],type:d}})},render:function(){var a=this.model,b=this.createSections();this.$el.html(this.template({id:a.get("innerContainerId"),sections:b,forum:a.get("sourceForum"),session:a.get("session").toJSON()}))},show:function(a){a.get("display")&&(this.$el.css({position:"static",
visibility:"visible"}),a.trigger("resize"))}})}(h);return{BaseCollectionView:k,TwoColumn:b,MainView:g}});
DISQUS.define("discovery.models",function(){var l=DISQUS.use("time"),h=function(a){var b=a.prototype;return a.extend({defaults:{redirectUrl:null,signedUrl:null,userId:null,sourceThreadId:null,forumId:null,forum:null,majorVersion:null,variant:null,isExperiment:!1},redirectPayload:function(){var a={url:this.get("signedUrl"),imp:DISQUS.juggler.impId,forum_id:this.get("forumId"),forum:this.get("forum"),thread_id:this.get("sourceThreadId"),major_version:this.get("majorVersion")};if(this.get("isExperiment"))a.variant=
this.get("variant");if(this.has("userId"))a.user_id=this.get("userId");if(this.collection&&this.collection.bandit)a.bandit=this.collection.getBanditJSON();return a},redirectUrl:function(){var a=this.get("redirectUrl"),b=this.redirectPayload();return DISQUS.serialize(a,b)},toJSON:function(){var a=b.toJSON.call(this);a.redirectUrl=this.redirectUrl();return a},toString:function(){return this.get("title")+" "+this.get("link")+" (id = "+this.id+")"}})}(Backbone.Model),k=function(a){var b=a.prototype;return a.extend({defaults:_.defaults({createdAgo:!1},
b.defaults),initialize:function(){if(this.get("createdAgo")){var a=l.assureTzOffset(this.get("createdAt")),a=moment(a,l.ISO_8601);this.set("createdAgo",a.fromNow())}},redirectPayload:function(){var a=b.redirectPayload.call(this);_.extend(a,{thread:this.id,zone:"internal_discovery"});return a},toJSON:function(){var a=b.toJSON.call(this);if(a.preview)a.preview=a.preview.toJSON();return a},toString:function(){return"organic link: "+b.toString.call(this)}})}(h),f=function(a){var b=a.prototype;return a.extend({idAttribute:"body_id",
defaults:_.defaults({brand:null,headline:null,text:null,url:null,advertisement_id:null,body_id:null,mobile:!0},b.defaults),get:function(a){if(a==="title")return this.attributes.headline;if(a==="link")return this.attributes.url;return b.get.call(this,a)},redirectPayload:function(){var a=b.redirectPayload.call(this);_.extend(a,{zone:"promoted_discovery",advertisement_id:this.get("advertisement_id")});if(this.has("body_id"))a.body_id=this.get("body_id");return a},toJSON:function(){var a=b.toJSON.call(this);
a.title=a.headline;a.link=a.url;return a},toString:function(){return"promoted link: "+b.toString.call(this)}})}(h),i=function(a){return a.extend({idAttribute:"advertisement_id",parse:function(a){a.signedUrl=a.signed_url;delete a.signed_url;return a}})}(f),k={RelatedThread:k,Advertisement:f,TempestAdvertisement:i};if(DISQUS.testing)k.BaseContentModel=h;return k});
DISQUS.define("discovery.helpers",function(l,h){var k=!1,f=!1,i=function(){};l.console&&(i=function(){if(f){var a=_.toArray(arguments);a.unshift("[Discovery]");l.console.log.apply?l.console.log.apply(l.console,a):l.console.log(a.join(" "))}});return{config:function(a){k=!!a.lineTruncationEnabled;f=!!a.consoleLoggingEnabled},isMobile:function(){return DISQUS.browser.mobile},log:i,allowLog:function(a){if(a===h)return f;f=!!a},allowLineTruncate:function(a){if(a===h)return k;k=!!a},lineTruncate:function(a,
b){function f(){return i.scrollHeight-i.offsetHeight>0.2*w}function c(){d.lastChild&&!_.contains(["...","\u2026"],d.lastChild.nodeValue)&&(q=d.appendChild(l.document.createTextNode(" "+u)),f()&&(d.removeChild(q),d.removeChild(d.lastChild),c()))}if(k){var h=DISQUS.logError||function(){};if(!a.closest("body").length)return void h("lineTruncate called on el not on DOM");if(a.text().length<1)return void h("lineTruncated called on empty el");if(_.any(a.children(),function(a){return a.nodeType!==3}))return void h("lineTruncate called on non-flat el");
var d=a[0],i=d;if(a.css("display")!=="block")for(;i.parentNode;)if(i=i.parentNode,$(i).css("display")==="block")break;var w=parseFloat(a.css("font-size"),10);if(f()){var b=b||{},h=b.lines||1,u=b.ellipsis,q,n=a.text();if(n.length){var s=a.width()/w,h=parseInt(s*h,10),n=n.split(/\s/),s=0;a.empty();for(var t=0,v=n.length;t<v;t++){s+=n[t].length+1;if(s>=h)break;d.appendChild(document.createTextNode(" "+n[t]))}if(f()){do q=d.removeChild(d.lastChild);while(f())}else{do q=d.appendChild(document.createTextNode(" "+
n[t++]));while(!f()&&t<v);d.removeChild(q)}u&&(_.isString(u)||(u="\u2026"),c())}}}},balancedPartition:function(a){var b=_.keys(a),f=Math.floor(_.reduce(a,function(a,b){return a+b},0)/2),c=b.length+1;f+=1;var h=Array(c),d,i;for(d=0;d<c;d++)h[d]=Array(f),h[d][0]={};for(i=1;i<f;i++)h[0][i]=!1;var k,l,q,n={};for(i=1;i<f;i++)for(d=1;d<c;d++){k=b[d-1];l=a[k];q=_.clone(h[d-1][i]);if(!q&&l<=i&&(q=_.clone(h[d-1][i-l])))q[k]=l,n=q;h[d][i]=q}return[n,_.omit(a,_.keys(n))]}}});